spring:
  application:
    name: cim-forward-route
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      jedis:
        pool:
          max-active: 100
          max-idle: 100
          max-wait: 1000
          min-idle: 10

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/cim-test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
#    username: root
#    password: zcyzcy159162


# web port
server:
  port: 8083

logging:
  level:
    root: info

  # enable swagger
springdoc:
  swagger-ui:
    enabled: true

app:
  zk:
    addr: 127.0.0.1:2181
    connect:
      timeout: 30000
    root: /route

  # route strategy
  #app.route.way=com.crossoverjie.cim.common.route.algorithm.loop.LoopHandle

  # route strategy
  #app.route.way=com.crossoverjie.cim.common.route.algorithm.random.RandomHandle

  # route strategy
  route:
    way:
      handler: com.crossoverjie.cim.common.route.algorithm.consistenthash.ConsistentHashHandle

  #app.route.way.consitenthash=com.crossoverjie.cim.common.route.algorithm.consistenthash.SortArrayMapConsistentHash

      consitenthash: com.crossoverjie.cim.common.route.algorithm.consistenthash.TreeMapConsistentHash

mybatis:
  configuration:
    map-underscore-to-camel-case: true # 自动驼峰转换
  type-aliases-package: com.crossoverjie.cim.persistence.api.pojo # 实体类包路径
  mapper-locations: classpath*:mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

offline:
  store:
    mode: redis
    redis:
      expire:
        message-ttl-days: 3

